### ISSUE TITLE
Deprecate kubeaudit

### ISSUE THREAD

**Issue by dani-santos-code** [Shopify/kubeaudit#593]
### Context

We should consider deprecating `kubeaudit` since Shopify's team hasn't been able to keep up with maintenance and cannot currently be efficient stewards.

We believe [kube-bench](https://github.com/aquasecurity/kube-bench) is a good successor. 

### Tasks

- [x] update README mentioning that the project isn't maintained and mention an alternative (`kube-bench`). Make changes to Issues and PR templates
- [x] update the code to add warnings (help +  running with flags)
- [x] make a new and last release
- [x] set up an announcement in [Discussions](https://github.com/Shopify/kubeaudit/discussions/new?category=announcements)
- [ ] finally archive the repo by the due date agreed on (October 2024)

**Comment by hrmcardle0** [comment]
Is there a large difference between the two, is it worth it for team to takeover ownership of this? I have not used it enough yet to determine this.

**Comment by dani-santos-code** [comment]
hi @hrmcardle0. which team are you talking about? 🤔
